spring:
  datasource:
    url: jdbc:h2:mem:retail_order;db_close_on_exit=false
    driver-class-name: org.h2.Driver
    username: inauth
    password: inauth
    platform: h2

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

    ROOT: ERROR

server:
  port: ${appPort:8088}
